FROM ghcr.io/puppeteer/puppeteer:<PPTR_VERSION>

ENV APPLICATION_USER=pptruser \
    APPLICATION_GROUP=pptruser \
    PPTR_VERSION=<PPTR_VERSION> \
    PATH="/home/pptruser/tools:${PATH}"

COPY tools tools

RUN mkdir screenshots
